title: evnto 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evnto.xyz" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Evangelos Ntomprozis
author-img:  profile_pic.jpg # add your photo
about-author: "Welcome to my personal small corner on the web. Enjoy my people-oriented content. "
social-facebook: vagelisnto
social-linkedin: vntomprozi
social-email: vagelisdob@gmail.com


# Disqus
discus-identifier: evnto-xyz

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
